config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get 'welcome/index'

  resources :couriers do
    resources :packages
  end

  root 'welcome#index'
end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/courier.rb
# frozen_string_literal: true

class Courier < ApplicationRecord
  has_many :packages, dependent: :destroy
  validates :name, presence: true
end

app/models/package.rb
# frozen_string_literal: true

class Package < ApplicationRecord
  belongs_to :courier
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
end

app/controllers/couriers_controller.rb
# frozen_string_literal: true

class CouriersController < ApplicationController
  def index
    @couriers = Courier.all
  end

  def show
    @courier = Courier.find(params[:id])
  end

  def new
    @courier = Courier.new
  end

  def edit
    @courier = Courier.find(params[:id])
  end

  def create
    @courier = Courier.new(courier_params)

    if @courier.save
      redirect_to @courier
    else
      render 'new'
    end
  end

  def update
    @courier = Courier.find(params[:id])

    if @courier.update(courier_params)
      redirect_to @courier
    else
      render 'edit'
    end
  end

  def destroy
    @courier = Courier.find(params[:id])
    @courier.destroy

    redirect_to couriers_path
  end

  private

  def courier_params
    params.require(:courier).permit(:name, :email)
  end
end

app/controllers/packages_controller.rb
# frozen_string_literal: true

class PackagesController < ApplicationController
  def create
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.create(package_params)
    redirect_to courier_path(@courier)
  end

  def destroy
    @courier = Courier.find(params[:courier_id])
    @package = @courier.packages.find(params[:id])
    @package.destroy
    redirect_to courier_path(@courier)
  end

  private

  def package_params
    params.require(:package).permit(:tracking_number, :delivery_status)
  end
end

app/controllers/welcome_controller.rb
# frozen_string_literal: true

class WelcomeController < ApplicationController
  def index; end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/couriers_helper.rb
# frozen_string_literal: true

module CouriersHelper
end

app/helpers/packages_helper.rb
# frozen_string_literal: true

module PackagesHelper
end

app/helpers/welcome_helper.rb
# frozen_string_literal: true

module WelcomeHelper
end

app/views/couriers/_form.html.erb
<%= form_with model: @courier, local: true do |form| %>

  <% if @courier.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@courier.errors.count, "error") %> prohibited
        this courier from being saved:
      </h2>
      <ul>
        <% @courier.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <p>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
  </p>

  <p>
    <%= form.label :email %><br>
    <%= form.email_field :email %>
  </p>

  <p>
    <%= form.submit %>
  </p>

<% end %>

app/views/couriers/edit.html.erb
<h1>Edit courier</h1>

<%= render 'form' %>

<%= link_to 'Back', couriers_path %>

app/views/couriers/index.html.erb
<h1>Listing couriers</h1>

<%= link_to 'New courier', new_courier_path %>

<table>
  <tr>
    <th>Name</th>
    <th>Email</th>
    <th></th>
  </tr>

  <% @couriers.each do |courier| %>
    <tr>
      <td><%= courier.name %></td>
      <td><%= courier.email %></td>
      <td><%= link_to 'Show', courier_path(courier) %></td>
      <td><%= link_to 'Edit', edit_courier_path(courier) %></td>
      <td><%= link_to 'Destroy', courier_path(courier),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/couriers/new.html.erb
<h1>New courier</h1>

<%= render 'form' %>

<%= link_to 'Back', couriers_path %>

app/views/couriers/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @courier.name %>
</p>

<p>
  <strong>Email:</strong>
  <%= @courier.email %>
</p>

<h2>Packages</h2>
<%= render @courier.packages %>
 
<h2>Add a package:</h2>
<%= render 'packages/form' %>

<%= link_to 'Edit', edit_courier_path(@courier) %> |
<%= link_to 'Back', couriers_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DeliveryApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/welcome/index.html.erb
<h1>Test task for Yalantis Ruby School!!!</h1>
<%= link_to 'Delivery app', controller: 'couriers' %>